# Generated by Django 4.2.7 on 2025-09-27 06:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Место, в котором необходимо выполнять привычку",
                        max_length=200,
                        verbose_name="Место выполнения",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="Время, когда необходимо выполнять привычку",
                        verbose_name="Время выполнения",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Действие, которое представляет собой привычка",
                        max_length=200,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Привычка, которую можно привязать к выполнению полезной привычки",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Периодичность выполнения привычки для напоминания в днях (от 1 до 7)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                        verbose_name="Периодичность в днях",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Чем пользователь должен себя вознаградить после выполнения",
                        max_length=200,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "execution_time",
                    models.PositiveIntegerField(
                        help_text="Время, которое предположительно потратит пользователь на выполнение привычки (не более 120 секунд)",
                        validators=[django.core.validators.MaxValueValidator(120)],
                        verbose_name="Время на выполнение в секундах",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Привычки можно публиковать в общий доступ",
                        verbose_name="Признак публичности",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Привычка, которая связана с другой привычкой",
                        limit_choices_to={"is_pleasant": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["-created_at"],
            },
        ),
    ]
